// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMovieInfoParams creates a new GetMovieInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMovieInfoParams() *GetMovieInfoParams {
	return &GetMovieInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMovieInfoParamsWithTimeout creates a new GetMovieInfoParams object
// with the ability to set a timeout on a request.
func NewGetMovieInfoParamsWithTimeout(timeout time.Duration) *GetMovieInfoParams {
	return &GetMovieInfoParams{
		timeout: timeout,
	}
}

// NewGetMovieInfoParamsWithContext creates a new GetMovieInfoParams object
// with the ability to set a context for a request.
func NewGetMovieInfoParamsWithContext(ctx context.Context) *GetMovieInfoParams {
	return &GetMovieInfoParams{
		Context: ctx,
	}
}

// NewGetMovieInfoParamsWithHTTPClient creates a new GetMovieInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMovieInfoParamsWithHTTPClient(client *http.Client) *GetMovieInfoParams {
	return &GetMovieInfoParams{
		HTTPClient: client,
	}
}

/*
GetMovieInfoParams contains all the parameters to send to the API endpoint

	for the get movie info operation.

	Typically these are written to a http.Request.
*/
type GetMovieInfoParams struct {

	/* ID.

	   ID фильма/сериала
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get movie info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMovieInfoParams) WithDefaults() *GetMovieInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get movie info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMovieInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get movie info params
func (o *GetMovieInfoParams) WithTimeout(timeout time.Duration) *GetMovieInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get movie info params
func (o *GetMovieInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get movie info params
func (o *GetMovieInfoParams) WithContext(ctx context.Context) *GetMovieInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get movie info params
func (o *GetMovieInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get movie info params
func (o *GetMovieInfoParams) WithHTTPClient(client *http.Client) *GetMovieInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get movie info params
func (o *GetMovieInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get movie info params
func (o *GetMovieInfoParams) WithID(id string) *GetMovieInfoParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get movie info params
func (o *GetMovieInfoParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetMovieInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
