// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/RacoonMediaServer/rms-media-discovery/pkg/client/models"
)

// GetMovieInfoReader is a Reader for the GetMovieInfo structure.
type GetMovieInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMovieInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMovieInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetMovieInfoNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetMovieInfoInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetMovieInfoOK creates a GetMovieInfoOK with default headers values
func NewGetMovieInfoOK() *GetMovieInfoOK {
	return &GetMovieInfoOK{}
}

/*
GetMovieInfoOK describes a response with status code 200, with default header values.

OK
*/
type GetMovieInfoOK struct {
	Payload *models.SearchMoviesResult
}

// IsSuccess returns true when this get movie info o k response has a 2xx status code
func (o *GetMovieInfoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get movie info o k response has a 3xx status code
func (o *GetMovieInfoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get movie info o k response has a 4xx status code
func (o *GetMovieInfoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get movie info o k response has a 5xx status code
func (o *GetMovieInfoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get movie info o k response a status code equal to that given
func (o *GetMovieInfoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get movie info o k response
func (o *GetMovieInfoOK) Code() int {
	return 200
}

func (o *GetMovieInfoOK) Error() string {
	return fmt.Sprintf("[GET /movies/{id}][%d] getMovieInfoOK  %+v", 200, o.Payload)
}

func (o *GetMovieInfoOK) String() string {
	return fmt.Sprintf("[GET /movies/{id}][%d] getMovieInfoOK  %+v", 200, o.Payload)
}

func (o *GetMovieInfoOK) GetPayload() *models.SearchMoviesResult {
	return o.Payload
}

func (o *GetMovieInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SearchMoviesResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMovieInfoNotFound creates a GetMovieInfoNotFound with default headers values
func NewGetMovieInfoNotFound() *GetMovieInfoNotFound {
	return &GetMovieInfoNotFound{}
}

/*
GetMovieInfoNotFound describes a response with status code 404, with default header values.

Фильм не найден
*/
type GetMovieInfoNotFound struct {
}

// IsSuccess returns true when this get movie info not found response has a 2xx status code
func (o *GetMovieInfoNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get movie info not found response has a 3xx status code
func (o *GetMovieInfoNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get movie info not found response has a 4xx status code
func (o *GetMovieInfoNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get movie info not found response has a 5xx status code
func (o *GetMovieInfoNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get movie info not found response a status code equal to that given
func (o *GetMovieInfoNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get movie info not found response
func (o *GetMovieInfoNotFound) Code() int {
	return 404
}

func (o *GetMovieInfoNotFound) Error() string {
	return fmt.Sprintf("[GET /movies/{id}][%d] getMovieInfoNotFound ", 404)
}

func (o *GetMovieInfoNotFound) String() string {
	return fmt.Sprintf("[GET /movies/{id}][%d] getMovieInfoNotFound ", 404)
}

func (o *GetMovieInfoNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMovieInfoInternalServerError creates a GetMovieInfoInternalServerError with default headers values
func NewGetMovieInfoInternalServerError() *GetMovieInfoInternalServerError {
	return &GetMovieInfoInternalServerError{}
}

/*
GetMovieInfoInternalServerError describes a response with status code 500, with default header values.

Ошибка на стороне сервера
*/
type GetMovieInfoInternalServerError struct {
}

// IsSuccess returns true when this get movie info internal server error response has a 2xx status code
func (o *GetMovieInfoInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get movie info internal server error response has a 3xx status code
func (o *GetMovieInfoInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get movie info internal server error response has a 4xx status code
func (o *GetMovieInfoInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get movie info internal server error response has a 5xx status code
func (o *GetMovieInfoInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get movie info internal server error response a status code equal to that given
func (o *GetMovieInfoInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get movie info internal server error response
func (o *GetMovieInfoInternalServerError) Code() int {
	return 500
}

func (o *GetMovieInfoInternalServerError) Error() string {
	return fmt.Sprintf("[GET /movies/{id}][%d] getMovieInfoInternalServerError ", 500)
}

func (o *GetMovieInfoInternalServerError) String() string {
	return fmt.Sprintf("[GET /movies/{id}][%d] getMovieInfoInternalServerError ", 500)
}

func (o *GetMovieInfoInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
