// Code generated by go-swagger; DO NOT EDIT.

package movies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSearchMoviesParams creates a new SearchMoviesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchMoviesParams() *SearchMoviesParams {
	return &SearchMoviesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchMoviesParamsWithTimeout creates a new SearchMoviesParams object
// with the ability to set a timeout on a request.
func NewSearchMoviesParamsWithTimeout(timeout time.Duration) *SearchMoviesParams {
	return &SearchMoviesParams{
		timeout: timeout,
	}
}

// NewSearchMoviesParamsWithContext creates a new SearchMoviesParams object
// with the ability to set a context for a request.
func NewSearchMoviesParamsWithContext(ctx context.Context) *SearchMoviesParams {
	return &SearchMoviesParams{
		Context: ctx,
	}
}

// NewSearchMoviesParamsWithHTTPClient creates a new SearchMoviesParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchMoviesParamsWithHTTPClient(client *http.Client) *SearchMoviesParams {
	return &SearchMoviesParams{
		HTTPClient: client,
	}
}

/*
SearchMoviesParams contains all the parameters to send to the API endpoint

	for the search movies operation.

	Typically these are written to a http.Request.
*/
type SearchMoviesParams struct {

	/* Limit.

	   Ограничение на кол-во результатов
	*/
	Limit *int64

	/* Q.

	   Искомый запрос
	*/
	Q string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search movies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchMoviesParams) WithDefaults() *SearchMoviesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search movies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchMoviesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search movies params
func (o *SearchMoviesParams) WithTimeout(timeout time.Duration) *SearchMoviesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search movies params
func (o *SearchMoviesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search movies params
func (o *SearchMoviesParams) WithContext(ctx context.Context) *SearchMoviesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search movies params
func (o *SearchMoviesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search movies params
func (o *SearchMoviesParams) WithHTTPClient(client *http.Client) *SearchMoviesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search movies params
func (o *SearchMoviesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the search movies params
func (o *SearchMoviesParams) WithLimit(limit *int64) *SearchMoviesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the search movies params
func (o *SearchMoviesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithQ adds the q to the search movies params
func (o *SearchMoviesParams) WithQ(q string) *SearchMoviesParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the search movies params
func (o *SearchMoviesParams) SetQ(q string) {
	o.Q = q
}

// WriteToRequest writes these params to a swagger request
func (o *SearchMoviesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// query param q
	qrQ := o.Q
	qQ := qrQ
	if qQ != "" {

		if err := r.SetQueryParam("q", qQ); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
