// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateAccountOKCode is the HTTP code returned for type CreateAccountOK
const CreateAccountOKCode int = 200

/*
CreateAccountOK OK

swagger:response createAccountOK
*/
type CreateAccountOK struct {

	/*
	  In: Body
	*/
	Payload *CreateAccountOKBody `json:"body,omitempty"`
}

// NewCreateAccountOK creates CreateAccountOK with default headers values
func NewCreateAccountOK() *CreateAccountOK {

	return &CreateAccountOK{}
}

// WithPayload adds the payload to the create account o k response
func (o *CreateAccountOK) WithPayload(payload *CreateAccountOKBody) *CreateAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account o k response
func (o *CreateAccountOK) SetPayload(payload *CreateAccountOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAccountInternalServerErrorCode is the HTTP code returned for type CreateAccountInternalServerError
const CreateAccountInternalServerErrorCode int = 500

/*
CreateAccountInternalServerError Ошибка на стороне сервера

swagger:response createAccountInternalServerError
*/
type CreateAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewCreateAccountInternalServerError creates CreateAccountInternalServerError with default headers values
func NewCreateAccountInternalServerError() *CreateAccountInternalServerError {

	return &CreateAccountInternalServerError{}
}

// WithPayload adds the payload to the create account internal server error response
func (o *CreateAccountInternalServerError) WithPayload(payload interface{}) *CreateAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account internal server error response
func (o *CreateAccountInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
