// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDownloadTorrentParams creates a new DownloadTorrentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDownloadTorrentParams() *DownloadTorrentParams {
	return &DownloadTorrentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDownloadTorrentParamsWithTimeout creates a new DownloadTorrentParams object
// with the ability to set a timeout on a request.
func NewDownloadTorrentParamsWithTimeout(timeout time.Duration) *DownloadTorrentParams {
	return &DownloadTorrentParams{
		timeout: timeout,
	}
}

// NewDownloadTorrentParamsWithContext creates a new DownloadTorrentParams object
// with the ability to set a context for a request.
func NewDownloadTorrentParamsWithContext(ctx context.Context) *DownloadTorrentParams {
	return &DownloadTorrentParams{
		Context: ctx,
	}
}

// NewDownloadTorrentParamsWithHTTPClient creates a new DownloadTorrentParams object
// with the ability to set a custom HTTPClient for a request.
func NewDownloadTorrentParamsWithHTTPClient(client *http.Client) *DownloadTorrentParams {
	return &DownloadTorrentParams{
		HTTPClient: client,
	}
}

/*
DownloadTorrentParams contains all the parameters to send to the API endpoint

	for the download torrent operation.

	Typically these are written to a http.Request.
*/
type DownloadTorrentParams struct {

	/* Link.

	   Хеш ссылки на результат поиска
	*/
	Link string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the download torrent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadTorrentParams) WithDefaults() *DownloadTorrentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the download torrent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadTorrentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the download torrent params
func (o *DownloadTorrentParams) WithTimeout(timeout time.Duration) *DownloadTorrentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the download torrent params
func (o *DownloadTorrentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the download torrent params
func (o *DownloadTorrentParams) WithContext(ctx context.Context) *DownloadTorrentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the download torrent params
func (o *DownloadTorrentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the download torrent params
func (o *DownloadTorrentParams) WithHTTPClient(client *http.Client) *DownloadTorrentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the download torrent params
func (o *DownloadTorrentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLink adds the link to the download torrent params
func (o *DownloadTorrentParams) WithLink(link string) *DownloadTorrentParams {
	o.SetLink(link)
	return o
}

// SetLink adds the link to the download torrent params
func (o *DownloadTorrentParams) SetLink(link string) {
	o.Link = link
}

// WriteToRequest writes these params to a swagger request
func (o *DownloadTorrentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param link
	qrLink := o.Link
	qLink := qrLink
	if qLink != "" {

		if err := r.SetQueryParam("link", qLink); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
