// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSearchTorrentsStatusParams creates a new GetSearchTorrentsStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSearchTorrentsStatusParams() *GetSearchTorrentsStatusParams {
	return &GetSearchTorrentsStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSearchTorrentsStatusParamsWithTimeout creates a new GetSearchTorrentsStatusParams object
// with the ability to set a timeout on a request.
func NewGetSearchTorrentsStatusParamsWithTimeout(timeout time.Duration) *GetSearchTorrentsStatusParams {
	return &GetSearchTorrentsStatusParams{
		timeout: timeout,
	}
}

// NewGetSearchTorrentsStatusParamsWithContext creates a new GetSearchTorrentsStatusParams object
// with the ability to set a context for a request.
func NewGetSearchTorrentsStatusParamsWithContext(ctx context.Context) *GetSearchTorrentsStatusParams {
	return &GetSearchTorrentsStatusParams{
		Context: ctx,
	}
}

// NewGetSearchTorrentsStatusParamsWithHTTPClient creates a new GetSearchTorrentsStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSearchTorrentsStatusParamsWithHTTPClient(client *http.Client) *GetSearchTorrentsStatusParams {
	return &GetSearchTorrentsStatusParams{
		HTTPClient: client,
	}
}

/*
GetSearchTorrentsStatusParams contains all the parameters to send to the API endpoint

	for the get search torrents status operation.

	Typically these are written to a http.Request.
*/
type GetSearchTorrentsStatusParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get search torrents status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSearchTorrentsStatusParams) WithDefaults() *GetSearchTorrentsStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get search torrents status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSearchTorrentsStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get search torrents status params
func (o *GetSearchTorrentsStatusParams) WithTimeout(timeout time.Duration) *GetSearchTorrentsStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get search torrents status params
func (o *GetSearchTorrentsStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get search torrents status params
func (o *GetSearchTorrentsStatusParams) WithContext(ctx context.Context) *GetSearchTorrentsStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get search torrents status params
func (o *GetSearchTorrentsStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get search torrents status params
func (o *GetSearchTorrentsStatusParams) WithHTTPClient(client *http.Client) *GetSearchTorrentsStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get search torrents status params
func (o *GetSearchTorrentsStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get search torrents status params
func (o *GetSearchTorrentsStatusParams) WithID(id string) *GetSearchTorrentsStatusParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get search torrents status params
func (o *GetSearchTorrentsStatusParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSearchTorrentsStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
