// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostTorrentSearchIDCancelParams creates a new PostTorrentSearchIDCancelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostTorrentSearchIDCancelParams() *PostTorrentSearchIDCancelParams {
	return &PostTorrentSearchIDCancelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostTorrentSearchIDCancelParamsWithTimeout creates a new PostTorrentSearchIDCancelParams object
// with the ability to set a timeout on a request.
func NewPostTorrentSearchIDCancelParamsWithTimeout(timeout time.Duration) *PostTorrentSearchIDCancelParams {
	return &PostTorrentSearchIDCancelParams{
		timeout: timeout,
	}
}

// NewPostTorrentSearchIDCancelParamsWithContext creates a new PostTorrentSearchIDCancelParams object
// with the ability to set a context for a request.
func NewPostTorrentSearchIDCancelParamsWithContext(ctx context.Context) *PostTorrentSearchIDCancelParams {
	return &PostTorrentSearchIDCancelParams{
		Context: ctx,
	}
}

// NewPostTorrentSearchIDCancelParamsWithHTTPClient creates a new PostTorrentSearchIDCancelParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostTorrentSearchIDCancelParamsWithHTTPClient(client *http.Client) *PostTorrentSearchIDCancelParams {
	return &PostTorrentSearchIDCancelParams{
		HTTPClient: client,
	}
}

/*
PostTorrentSearchIDCancelParams contains all the parameters to send to the API endpoint

	for the post torrent search ID cancel operation.

	Typically these are written to a http.Request.
*/
type PostTorrentSearchIDCancelParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post torrent search ID cancel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTorrentSearchIDCancelParams) WithDefaults() *PostTorrentSearchIDCancelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post torrent search ID cancel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTorrentSearchIDCancelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post torrent search ID cancel params
func (o *PostTorrentSearchIDCancelParams) WithTimeout(timeout time.Duration) *PostTorrentSearchIDCancelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post torrent search ID cancel params
func (o *PostTorrentSearchIDCancelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post torrent search ID cancel params
func (o *PostTorrentSearchIDCancelParams) WithContext(ctx context.Context) *PostTorrentSearchIDCancelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post torrent search ID cancel params
func (o *PostTorrentSearchIDCancelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post torrent search ID cancel params
func (o *PostTorrentSearchIDCancelParams) WithHTTPClient(client *http.Client) *PostTorrentSearchIDCancelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post torrent search ID cancel params
func (o *PostTorrentSearchIDCancelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post torrent search ID cancel params
func (o *PostTorrentSearchIDCancelParams) WithID(id string) *PostTorrentSearchIDCancelParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post torrent search ID cancel params
func (o *PostTorrentSearchIDCancelParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostTorrentSearchIDCancelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
