// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSearchTorrentsParams creates a new SearchTorrentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchTorrentsParams() *SearchTorrentsParams {
	return &SearchTorrentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchTorrentsParamsWithTimeout creates a new SearchTorrentsParams object
// with the ability to set a timeout on a request.
func NewSearchTorrentsParamsWithTimeout(timeout time.Duration) *SearchTorrentsParams {
	return &SearchTorrentsParams{
		timeout: timeout,
	}
}

// NewSearchTorrentsParamsWithContext creates a new SearchTorrentsParams object
// with the ability to set a context for a request.
func NewSearchTorrentsParamsWithContext(ctx context.Context) *SearchTorrentsParams {
	return &SearchTorrentsParams{
		Context: ctx,
	}
}

// NewSearchTorrentsParamsWithHTTPClient creates a new SearchTorrentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchTorrentsParamsWithHTTPClient(client *http.Client) *SearchTorrentsParams {
	return &SearchTorrentsParams{
		HTTPClient: client,
	}
}

/*
SearchTorrentsParams contains all the parameters to send to the API endpoint

	for the search torrents operation.

	Typically these are written to a http.Request.
*/
type SearchTorrentsParams struct {

	/* Detailed.

	   Забирать ли детальное описание раздачи
	*/
	Detailed *bool

	/* Limit.

	   Ограничение на кол-во результатов
	*/
	Limit *int64

	// Orderby.
	//
	// Default: "seeders"
	Orderby *string

	/* Q.

	   Искомый запрос
	*/
	Q string

	/* Season.

	   Номер сезона (для сериалов)
	*/
	Season *int64

	/* Type.

	   Подсказка, какого типа торренты искать
	*/
	Type *string

	/* Year.

	   Год выхода (для фильмов и сериалов)
	*/
	Year *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search torrents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchTorrentsParams) WithDefaults() *SearchTorrentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search torrents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchTorrentsParams) SetDefaults() {
	var (
		detailedDefault = bool(false)

		orderbyDefault = string("seeders")
	)

	val := SearchTorrentsParams{
		Detailed: &detailedDefault,
		Orderby:  &orderbyDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the search torrents params
func (o *SearchTorrentsParams) WithTimeout(timeout time.Duration) *SearchTorrentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search torrents params
func (o *SearchTorrentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search torrents params
func (o *SearchTorrentsParams) WithContext(ctx context.Context) *SearchTorrentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search torrents params
func (o *SearchTorrentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search torrents params
func (o *SearchTorrentsParams) WithHTTPClient(client *http.Client) *SearchTorrentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search torrents params
func (o *SearchTorrentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDetailed adds the detailed to the search torrents params
func (o *SearchTorrentsParams) WithDetailed(detailed *bool) *SearchTorrentsParams {
	o.SetDetailed(detailed)
	return o
}

// SetDetailed adds the detailed to the search torrents params
func (o *SearchTorrentsParams) SetDetailed(detailed *bool) {
	o.Detailed = detailed
}

// WithLimit adds the limit to the search torrents params
func (o *SearchTorrentsParams) WithLimit(limit *int64) *SearchTorrentsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the search torrents params
func (o *SearchTorrentsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOrderby adds the orderby to the search torrents params
func (o *SearchTorrentsParams) WithOrderby(orderby *string) *SearchTorrentsParams {
	o.SetOrderby(orderby)
	return o
}

// SetOrderby adds the orderby to the search torrents params
func (o *SearchTorrentsParams) SetOrderby(orderby *string) {
	o.Orderby = orderby
}

// WithQ adds the q to the search torrents params
func (o *SearchTorrentsParams) WithQ(q string) *SearchTorrentsParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the search torrents params
func (o *SearchTorrentsParams) SetQ(q string) {
	o.Q = q
}

// WithSeason adds the season to the search torrents params
func (o *SearchTorrentsParams) WithSeason(season *int64) *SearchTorrentsParams {
	o.SetSeason(season)
	return o
}

// SetSeason adds the season to the search torrents params
func (o *SearchTorrentsParams) SetSeason(season *int64) {
	o.Season = season
}

// WithType adds the typeVar to the search torrents params
func (o *SearchTorrentsParams) WithType(typeVar *string) *SearchTorrentsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the search torrents params
func (o *SearchTorrentsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WithYear adds the year to the search torrents params
func (o *SearchTorrentsParams) WithYear(year *int64) *SearchTorrentsParams {
	o.SetYear(year)
	return o
}

// SetYear adds the year to the search torrents params
func (o *SearchTorrentsParams) SetYear(year *int64) {
	o.Year = year
}

// WriteToRequest writes these params to a swagger request
func (o *SearchTorrentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Detailed != nil {

		// query param detailed
		var qrDetailed bool

		if o.Detailed != nil {
			qrDetailed = *o.Detailed
		}
		qDetailed := swag.FormatBool(qrDetailed)
		if qDetailed != "" {

			if err := r.SetQueryParam("detailed", qDetailed); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Orderby != nil {

		// query param orderby
		var qrOrderby string

		if o.Orderby != nil {
			qrOrderby = *o.Orderby
		}
		qOrderby := qrOrderby
		if qOrderby != "" {

			if err := r.SetQueryParam("orderby", qOrderby); err != nil {
				return err
			}
		}
	}

	// query param q
	qrQ := o.Q
	qQ := qrQ
	if qQ != "" {

		if err := r.SetQueryParam("q", qQ); err != nil {
			return err
		}
	}

	if o.Season != nil {

		// query param season
		var qrSeason int64

		if o.Season != nil {
			qrSeason = *o.Season
		}
		qSeason := swag.FormatInt64(qrSeason)
		if qSeason != "" {

			if err := r.SetQueryParam("season", qSeason); err != nil {
				return err
			}
		}
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if o.Year != nil {

		// query param year
		var qrYear int64

		if o.Year != nil {
			qrYear = *o.Year
		}
		qYear := swag.FormatInt64(qrYear)
		if qYear != "" {

			if err := r.SetQueryParam("year", qYear); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
