// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSearchTorrentsParams creates a new SearchTorrentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchTorrentsParams() *SearchTorrentsParams {
	return &SearchTorrentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchTorrentsParamsWithTimeout creates a new SearchTorrentsParams object
// with the ability to set a timeout on a request.
func NewSearchTorrentsParamsWithTimeout(timeout time.Duration) *SearchTorrentsParams {
	return &SearchTorrentsParams{
		timeout: timeout,
	}
}

// NewSearchTorrentsParamsWithContext creates a new SearchTorrentsParams object
// with the ability to set a context for a request.
func NewSearchTorrentsParamsWithContext(ctx context.Context) *SearchTorrentsParams {
	return &SearchTorrentsParams{
		Context: ctx,
	}
}

// NewSearchTorrentsParamsWithHTTPClient creates a new SearchTorrentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchTorrentsParamsWithHTTPClient(client *http.Client) *SearchTorrentsParams {
	return &SearchTorrentsParams{
		HTTPClient: client,
	}
}

/*
SearchTorrentsParams contains all the parameters to send to the API endpoint

	for the search torrents operation.

	Typically these are written to a http.Request.
*/
type SearchTorrentsParams struct {

	/* Limit.

	   Ограничение на кол-во результатов
	*/
	Limit *int64

	/* Q.

	   Искомый запрос
	*/
	Q string

	/* Type.

	   Подсказка, какого типа инфу искать
	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search torrents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchTorrentsParams) WithDefaults() *SearchTorrentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search torrents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchTorrentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search torrents params
func (o *SearchTorrentsParams) WithTimeout(timeout time.Duration) *SearchTorrentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search torrents params
func (o *SearchTorrentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search torrents params
func (o *SearchTorrentsParams) WithContext(ctx context.Context) *SearchTorrentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search torrents params
func (o *SearchTorrentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search torrents params
func (o *SearchTorrentsParams) WithHTTPClient(client *http.Client) *SearchTorrentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search torrents params
func (o *SearchTorrentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the search torrents params
func (o *SearchTorrentsParams) WithLimit(limit *int64) *SearchTorrentsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the search torrents params
func (o *SearchTorrentsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithQ adds the q to the search torrents params
func (o *SearchTorrentsParams) WithQ(q string) *SearchTorrentsParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the search torrents params
func (o *SearchTorrentsParams) SetQ(q string) {
	o.Q = q
}

// WithType adds the typeVar to the search torrents params
func (o *SearchTorrentsParams) WithType(typeVar *string) *SearchTorrentsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the search torrents params
func (o *SearchTorrentsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *SearchTorrentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// query param q
	qrQ := o.Q
	qQ := qrQ
	if qQ != "" {

		if err := r.SetQueryParam("q", qQ); err != nil {
			return err
		}
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
