// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/RacoonMediaServer/rms-media-discovery/pkg/client/models"
)

// SearchTorrentsAsyncStatusReader is a Reader for the SearchTorrentsAsyncStatus structure.
type SearchTorrentsAsyncStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchTorrentsAsyncStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchTorrentsAsyncStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewSearchTorrentsAsyncStatusNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSearchTorrentsAsyncStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /torrents/search/{id}:status] searchTorrentsAsyncStatus", response, response.Code())
	}
}

// NewSearchTorrentsAsyncStatusOK creates a SearchTorrentsAsyncStatusOK with default headers values
func NewSearchTorrentsAsyncStatusOK() *SearchTorrentsAsyncStatusOK {
	return &SearchTorrentsAsyncStatusOK{}
}

/*
SearchTorrentsAsyncStatusOK describes a response with status code 200, with default header values.

OK
*/
type SearchTorrentsAsyncStatusOK struct {
	Payload *SearchTorrentsAsyncStatusOKBody
}

// IsSuccess returns true when this search torrents async status o k response has a 2xx status code
func (o *SearchTorrentsAsyncStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search torrents async status o k response has a 3xx status code
func (o *SearchTorrentsAsyncStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search torrents async status o k response has a 4xx status code
func (o *SearchTorrentsAsyncStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search torrents async status o k response has a 5xx status code
func (o *SearchTorrentsAsyncStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search torrents async status o k response a status code equal to that given
func (o *SearchTorrentsAsyncStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the search torrents async status o k response
func (o *SearchTorrentsAsyncStatusOK) Code() int {
	return 200
}

func (o *SearchTorrentsAsyncStatusOK) Error() string {
	return fmt.Sprintf("[GET /torrents/search/{id}:status][%d] searchTorrentsAsyncStatusOK  %+v", 200, o.Payload)
}

func (o *SearchTorrentsAsyncStatusOK) String() string {
	return fmt.Sprintf("[GET /torrents/search/{id}:status][%d] searchTorrentsAsyncStatusOK  %+v", 200, o.Payload)
}

func (o *SearchTorrentsAsyncStatusOK) GetPayload() *SearchTorrentsAsyncStatusOKBody {
	return o.Payload
}

func (o *SearchTorrentsAsyncStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SearchTorrentsAsyncStatusOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchTorrentsAsyncStatusNotFound creates a SearchTorrentsAsyncStatusNotFound with default headers values
func NewSearchTorrentsAsyncStatusNotFound() *SearchTorrentsAsyncStatusNotFound {
	return &SearchTorrentsAsyncStatusNotFound{}
}

/*
SearchTorrentsAsyncStatusNotFound describes a response with status code 404, with default header values.

Задача поиска не найдена
*/
type SearchTorrentsAsyncStatusNotFound struct {
}

// IsSuccess returns true when this search torrents async status not found response has a 2xx status code
func (o *SearchTorrentsAsyncStatusNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search torrents async status not found response has a 3xx status code
func (o *SearchTorrentsAsyncStatusNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search torrents async status not found response has a 4xx status code
func (o *SearchTorrentsAsyncStatusNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this search torrents async status not found response has a 5xx status code
func (o *SearchTorrentsAsyncStatusNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this search torrents async status not found response a status code equal to that given
func (o *SearchTorrentsAsyncStatusNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the search torrents async status not found response
func (o *SearchTorrentsAsyncStatusNotFound) Code() int {
	return 404
}

func (o *SearchTorrentsAsyncStatusNotFound) Error() string {
	return fmt.Sprintf("[GET /torrents/search/{id}:status][%d] searchTorrentsAsyncStatusNotFound ", 404)
}

func (o *SearchTorrentsAsyncStatusNotFound) String() string {
	return fmt.Sprintf("[GET /torrents/search/{id}:status][%d] searchTorrentsAsyncStatusNotFound ", 404)
}

func (o *SearchTorrentsAsyncStatusNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSearchTorrentsAsyncStatusInternalServerError creates a SearchTorrentsAsyncStatusInternalServerError with default headers values
func NewSearchTorrentsAsyncStatusInternalServerError() *SearchTorrentsAsyncStatusInternalServerError {
	return &SearchTorrentsAsyncStatusInternalServerError{}
}

/*
SearchTorrentsAsyncStatusInternalServerError describes a response with status code 500, with default header values.

Ошибка на стороне сервера
*/
type SearchTorrentsAsyncStatusInternalServerError struct {
}

// IsSuccess returns true when this search torrents async status internal server error response has a 2xx status code
func (o *SearchTorrentsAsyncStatusInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search torrents async status internal server error response has a 3xx status code
func (o *SearchTorrentsAsyncStatusInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search torrents async status internal server error response has a 4xx status code
func (o *SearchTorrentsAsyncStatusInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this search torrents async status internal server error response has a 5xx status code
func (o *SearchTorrentsAsyncStatusInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this search torrents async status internal server error response a status code equal to that given
func (o *SearchTorrentsAsyncStatusInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the search torrents async status internal server error response
func (o *SearchTorrentsAsyncStatusInternalServerError) Code() int {
	return 500
}

func (o *SearchTorrentsAsyncStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /torrents/search/{id}:status][%d] searchTorrentsAsyncStatusInternalServerError ", 500)
}

func (o *SearchTorrentsAsyncStatusInternalServerError) String() string {
	return fmt.Sprintf("[GET /torrents/search/{id}:status][%d] searchTorrentsAsyncStatusInternalServerError ", 500)
}

func (o *SearchTorrentsAsyncStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
SearchTorrentsAsyncStatusOKBody search torrents async status o k body
swagger:model SearchTorrentsAsyncStatusOKBody
*/
type SearchTorrentsAsyncStatusOKBody struct {

	// error
	Error string `json:"error,omitempty"`

	// results
	Results []*models.SearchTorrentsResult `json:"results"`

	// status
	// Required: true
	// Enum: [working ready error]
	Status *string `json:"status"`
}

// Validate validates this search torrents async status o k body
func (o *SearchTorrentsAsyncStatusOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SearchTorrentsAsyncStatusOKBody) validateResults(formats strfmt.Registry) error {
	if swag.IsZero(o.Results) { // not required
		return nil
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("searchTorrentsAsyncStatusOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("searchTorrentsAsyncStatusOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var searchTorrentsAsyncStatusOKBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["working","ready","error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		searchTorrentsAsyncStatusOKBodyTypeStatusPropEnum = append(searchTorrentsAsyncStatusOKBodyTypeStatusPropEnum, v)
	}
}

const (

	// SearchTorrentsAsyncStatusOKBodyStatusWorking captures enum value "working"
	SearchTorrentsAsyncStatusOKBodyStatusWorking string = "working"

	// SearchTorrentsAsyncStatusOKBodyStatusReady captures enum value "ready"
	SearchTorrentsAsyncStatusOKBodyStatusReady string = "ready"

	// SearchTorrentsAsyncStatusOKBodyStatusError captures enum value "error"
	SearchTorrentsAsyncStatusOKBodyStatusError string = "error"
)

// prop value enum
func (o *SearchTorrentsAsyncStatusOKBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, searchTorrentsAsyncStatusOKBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *SearchTorrentsAsyncStatusOKBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("searchTorrentsAsyncStatusOK"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	// value enum
	if err := o.validateStatusEnum("searchTorrentsAsyncStatusOK"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this search torrents async status o k body based on the context it is used
func (o *SearchTorrentsAsyncStatusOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResults(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SearchTorrentsAsyncStatusOKBody) contextValidateResults(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Results); i++ {

		if o.Results[i] != nil {

			if swag.IsZero(o.Results[i]) { // not required
				return nil
			}

			if err := o.Results[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("searchTorrentsAsyncStatusOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("searchTorrentsAsyncStatusOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *SearchTorrentsAsyncStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SearchTorrentsAsyncStatusOKBody) UnmarshalBinary(b []byte) error {
	var res SearchTorrentsAsyncStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
