// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSearchTorrentsAsyncParams creates a new SearchTorrentsAsyncParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchTorrentsAsyncParams() *SearchTorrentsAsyncParams {
	return &SearchTorrentsAsyncParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchTorrentsAsyncParamsWithTimeout creates a new SearchTorrentsAsyncParams object
// with the ability to set a timeout on a request.
func NewSearchTorrentsAsyncParamsWithTimeout(timeout time.Duration) *SearchTorrentsAsyncParams {
	return &SearchTorrentsAsyncParams{
		timeout: timeout,
	}
}

// NewSearchTorrentsAsyncParamsWithContext creates a new SearchTorrentsAsyncParams object
// with the ability to set a context for a request.
func NewSearchTorrentsAsyncParamsWithContext(ctx context.Context) *SearchTorrentsAsyncParams {
	return &SearchTorrentsAsyncParams{
		Context: ctx,
	}
}

// NewSearchTorrentsAsyncParamsWithHTTPClient creates a new SearchTorrentsAsyncParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchTorrentsAsyncParamsWithHTTPClient(client *http.Client) *SearchTorrentsAsyncParams {
	return &SearchTorrentsAsyncParams{
		HTTPClient: client,
	}
}

/*
SearchTorrentsAsyncParams contains all the parameters to send to the API endpoint

	for the search torrents async operation.

	Typically these are written to a http.Request.
*/
type SearchTorrentsAsyncParams struct {

	// SearchParameters.
	SearchParameters SearchTorrentsAsyncBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search torrents async params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchTorrentsAsyncParams) WithDefaults() *SearchTorrentsAsyncParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search torrents async params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchTorrentsAsyncParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search torrents async params
func (o *SearchTorrentsAsyncParams) WithTimeout(timeout time.Duration) *SearchTorrentsAsyncParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search torrents async params
func (o *SearchTorrentsAsyncParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search torrents async params
func (o *SearchTorrentsAsyncParams) WithContext(ctx context.Context) *SearchTorrentsAsyncParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search torrents async params
func (o *SearchTorrentsAsyncParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search torrents async params
func (o *SearchTorrentsAsyncParams) WithHTTPClient(client *http.Client) *SearchTorrentsAsyncParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search torrents async params
func (o *SearchTorrentsAsyncParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSearchParameters adds the searchParameters to the search torrents async params
func (o *SearchTorrentsAsyncParams) WithSearchParameters(searchParameters SearchTorrentsAsyncBody) *SearchTorrentsAsyncParams {
	o.SetSearchParameters(searchParameters)
	return o
}

// SetSearchParameters adds the searchParameters to the search torrents async params
func (o *SearchTorrentsAsyncParams) SetSearchParameters(searchParameters SearchTorrentsAsyncBody) {
	o.SearchParameters = searchParameters
}

// WriteToRequest writes these params to a swagger request
func (o *SearchTorrentsAsyncParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.SearchParameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
