// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSearchTorrentsAsyncCancelParams creates a new SearchTorrentsAsyncCancelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchTorrentsAsyncCancelParams() *SearchTorrentsAsyncCancelParams {
	return &SearchTorrentsAsyncCancelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchTorrentsAsyncCancelParamsWithTimeout creates a new SearchTorrentsAsyncCancelParams object
// with the ability to set a timeout on a request.
func NewSearchTorrentsAsyncCancelParamsWithTimeout(timeout time.Duration) *SearchTorrentsAsyncCancelParams {
	return &SearchTorrentsAsyncCancelParams{
		timeout: timeout,
	}
}

// NewSearchTorrentsAsyncCancelParamsWithContext creates a new SearchTorrentsAsyncCancelParams object
// with the ability to set a context for a request.
func NewSearchTorrentsAsyncCancelParamsWithContext(ctx context.Context) *SearchTorrentsAsyncCancelParams {
	return &SearchTorrentsAsyncCancelParams{
		Context: ctx,
	}
}

// NewSearchTorrentsAsyncCancelParamsWithHTTPClient creates a new SearchTorrentsAsyncCancelParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchTorrentsAsyncCancelParamsWithHTTPClient(client *http.Client) *SearchTorrentsAsyncCancelParams {
	return &SearchTorrentsAsyncCancelParams{
		HTTPClient: client,
	}
}

/*
SearchTorrentsAsyncCancelParams contains all the parameters to send to the API endpoint

	for the search torrents async cancel operation.

	Typically these are written to a http.Request.
*/
type SearchTorrentsAsyncCancelParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search torrents async cancel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchTorrentsAsyncCancelParams) WithDefaults() *SearchTorrentsAsyncCancelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search torrents async cancel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchTorrentsAsyncCancelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search torrents async cancel params
func (o *SearchTorrentsAsyncCancelParams) WithTimeout(timeout time.Duration) *SearchTorrentsAsyncCancelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search torrents async cancel params
func (o *SearchTorrentsAsyncCancelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search torrents async cancel params
func (o *SearchTorrentsAsyncCancelParams) WithContext(ctx context.Context) *SearchTorrentsAsyncCancelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search torrents async cancel params
func (o *SearchTorrentsAsyncCancelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search torrents async cancel params
func (o *SearchTorrentsAsyncCancelParams) WithHTTPClient(client *http.Client) *SearchTorrentsAsyncCancelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search torrents async cancel params
func (o *SearchTorrentsAsyncCancelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the search torrents async cancel params
func (o *SearchTorrentsAsyncCancelParams) WithID(id string) *SearchTorrentsAsyncCancelParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the search torrents async cancel params
func (o *SearchTorrentsAsyncCancelParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SearchTorrentsAsyncCancelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
