// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DownloadTorrentOKCode is the HTTP code returned for type DownloadTorrentOK
const DownloadTorrentOKCode int = 200

/*
DownloadTorrentOK OK

swagger:response downloadTorrentOK
*/
type DownloadTorrentOK struct {
}

// NewDownloadTorrentOK creates DownloadTorrentOK with default headers values
func NewDownloadTorrentOK() *DownloadTorrentOK {

	return &DownloadTorrentOK{}
}

// WriteResponse to the client
func (o *DownloadTorrentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DownloadTorrentNotFoundCode is the HTTP code returned for type DownloadTorrentNotFound
const DownloadTorrentNotFoundCode int = 404

/*
DownloadTorrentNotFound Неверный хеш ссылки

swagger:response downloadTorrentNotFound
*/
type DownloadTorrentNotFound struct {
}

// NewDownloadTorrentNotFound creates DownloadTorrentNotFound with default headers values
func NewDownloadTorrentNotFound() *DownloadTorrentNotFound {

	return &DownloadTorrentNotFound{}
}

// WriteResponse to the client
func (o *DownloadTorrentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DownloadTorrentInternalServerErrorCode is the HTTP code returned for type DownloadTorrentInternalServerError
const DownloadTorrentInternalServerErrorCode int = 500

/*
DownloadTorrentInternalServerError Ошибка на стороне сервера

swagger:response downloadTorrentInternalServerError
*/
type DownloadTorrentInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewDownloadTorrentInternalServerError creates DownloadTorrentInternalServerError with default headers values
func NewDownloadTorrentInternalServerError() *DownloadTorrentInternalServerError {

	return &DownloadTorrentInternalServerError{}
}

// WithPayload adds the payload to the download torrent internal server error response
func (o *DownloadTorrentInternalServerError) WithPayload(payload interface{}) *DownloadTorrentInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download torrent internal server error response
func (o *DownloadTorrentInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadTorrentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
