// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DownloadTorrentOKCode is the HTTP code returned for type DownloadTorrentOK
const DownloadTorrentOKCode int = 200

/*
DownloadTorrentOK OK

swagger:response downloadTorrentOK
*/
type DownloadTorrentOK struct {
}

// NewDownloadTorrentOK creates DownloadTorrentOK with default headers values
func NewDownloadTorrentOK() *DownloadTorrentOK {

	return &DownloadTorrentOK{}
}

// WriteResponse to the client
func (o *DownloadTorrentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DownloadTorrentNotFoundCode is the HTTP code returned for type DownloadTorrentNotFound
const DownloadTorrentNotFoundCode int = 404

/*
DownloadTorrentNotFound Неверный хеш ссылки

swagger:response downloadTorrentNotFound
*/
type DownloadTorrentNotFound struct {
}

// NewDownloadTorrentNotFound creates DownloadTorrentNotFound with default headers values
func NewDownloadTorrentNotFound() *DownloadTorrentNotFound {

	return &DownloadTorrentNotFound{}
}

// WriteResponse to the client
func (o *DownloadTorrentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DownloadTorrentInternalServerErrorCode is the HTTP code returned for type DownloadTorrentInternalServerError
const DownloadTorrentInternalServerErrorCode int = 500

/*
DownloadTorrentInternalServerError Ошибка на стороне сервера

swagger:response downloadTorrentInternalServerError
*/
type DownloadTorrentInternalServerError struct {
}

// NewDownloadTorrentInternalServerError creates DownloadTorrentInternalServerError with default headers values
func NewDownloadTorrentInternalServerError() *DownloadTorrentInternalServerError {

	return &DownloadTorrentInternalServerError{}
}

// WriteResponse to the client
func (o *DownloadTorrentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
