// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetSearchTorrentsStatusOKCode is the HTTP code returned for type GetSearchTorrentsStatusOK
const GetSearchTorrentsStatusOKCode int = 200

/*
GetSearchTorrentsStatusOK OK

swagger:response getSearchTorrentsStatusOK
*/
type GetSearchTorrentsStatusOK struct {

	/*
	  In: Body
	*/
	Payload *GetSearchTorrentsStatusOKBody `json:"body,omitempty"`
}

// NewGetSearchTorrentsStatusOK creates GetSearchTorrentsStatusOK with default headers values
func NewGetSearchTorrentsStatusOK() *GetSearchTorrentsStatusOK {

	return &GetSearchTorrentsStatusOK{}
}

// WithPayload adds the payload to the get search torrents status o k response
func (o *GetSearchTorrentsStatusOK) WithPayload(payload *GetSearchTorrentsStatusOKBody) *GetSearchTorrentsStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get search torrents status o k response
func (o *GetSearchTorrentsStatusOK) SetPayload(payload *GetSearchTorrentsStatusOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSearchTorrentsStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSearchTorrentsStatusNotFoundCode is the HTTP code returned for type GetSearchTorrentsStatusNotFound
const GetSearchTorrentsStatusNotFoundCode int = 404

/*
GetSearchTorrentsStatusNotFound Задача поиска не найдена

swagger:response getSearchTorrentsStatusNotFound
*/
type GetSearchTorrentsStatusNotFound struct {
}

// NewGetSearchTorrentsStatusNotFound creates GetSearchTorrentsStatusNotFound with default headers values
func NewGetSearchTorrentsStatusNotFound() *GetSearchTorrentsStatusNotFound {

	return &GetSearchTorrentsStatusNotFound{}
}

// WriteResponse to the client
func (o *GetSearchTorrentsStatusNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetSearchTorrentsStatusInternalServerErrorCode is the HTTP code returned for type GetSearchTorrentsStatusInternalServerError
const GetSearchTorrentsStatusInternalServerErrorCode int = 500

/*
GetSearchTorrentsStatusInternalServerError Ошибка на стороне сервера

swagger:response getSearchTorrentsStatusInternalServerError
*/
type GetSearchTorrentsStatusInternalServerError struct {
}

// NewGetSearchTorrentsStatusInternalServerError creates GetSearchTorrentsStatusInternalServerError with default headers values
func NewGetSearchTorrentsStatusInternalServerError() *GetSearchTorrentsStatusInternalServerError {

	return &GetSearchTorrentsStatusInternalServerError{}
}

// WriteResponse to the client
func (o *GetSearchTorrentsStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
