// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/RacoonMediaServer/rms-media-discovery/internal/server/models"
)

// GetSearchTorrentsStatusHandlerFunc turns a function with the right signature into a get search torrents status handler
type GetSearchTorrentsStatusHandlerFunc func(GetSearchTorrentsStatusParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSearchTorrentsStatusHandlerFunc) Handle(params GetSearchTorrentsStatusParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetSearchTorrentsStatusHandler interface for that can handle valid get search torrents status params
type GetSearchTorrentsStatusHandler interface {
	Handle(GetSearchTorrentsStatusParams, *models.Principal) middleware.Responder
}

// NewGetSearchTorrentsStatus creates a new http.Handler for the get search torrents status operation
func NewGetSearchTorrentsStatus(ctx *middleware.Context, handler GetSearchTorrentsStatusHandler) *GetSearchTorrentsStatus {
	return &GetSearchTorrentsStatus{Context: ctx, Handler: handler}
}

/*
	GetSearchTorrentsStatus swagger:route GET /torrents/search/{id}:status torrents getSearchTorrentsStatus

# Узнать статус задачи поиска

Запросить статус и результаты задачи поиска
*/
type GetSearchTorrentsStatus struct {
	Context *middleware.Context
	Handler GetSearchTorrentsStatusHandler
}

func (o *GetSearchTorrentsStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSearchTorrentsStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetSearchTorrentsStatusOKBody get search torrents status o k body
//
// swagger:model GetSearchTorrentsStatusOKBody
type GetSearchTorrentsStatusOKBody struct {

	// error
	Error string `json:"error,omitempty"`

	// results
	Results []*models.SearchTorrentsResult `json:"results"`

	// status
	// Required: true
	// Enum: [working ready error]
	Status *string `json:"status"`
}

// Validate validates this get search torrents status o k body
func (o *GetSearchTorrentsStatusOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSearchTorrentsStatusOKBody) validateResults(formats strfmt.Registry) error {
	if swag.IsZero(o.Results) { // not required
		return nil
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getSearchTorrentsStatusOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getSearchTorrentsStatusOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var getSearchTorrentsStatusOKBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["working","ready","error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getSearchTorrentsStatusOKBodyTypeStatusPropEnum = append(getSearchTorrentsStatusOKBodyTypeStatusPropEnum, v)
	}
}

const (

	// GetSearchTorrentsStatusOKBodyStatusWorking captures enum value "working"
	GetSearchTorrentsStatusOKBodyStatusWorking string = "working"

	// GetSearchTorrentsStatusOKBodyStatusReady captures enum value "ready"
	GetSearchTorrentsStatusOKBodyStatusReady string = "ready"

	// GetSearchTorrentsStatusOKBodyStatusError captures enum value "error"
	GetSearchTorrentsStatusOKBodyStatusError string = "error"
)

// prop value enum
func (o *GetSearchTorrentsStatusOKBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getSearchTorrentsStatusOKBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetSearchTorrentsStatusOKBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("getSearchTorrentsStatusOK"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	// value enum
	if err := o.validateStatusEnum("getSearchTorrentsStatusOK"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this get search torrents status o k body based on the context it is used
func (o *GetSearchTorrentsStatusOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResults(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSearchTorrentsStatusOKBody) contextValidateResults(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Results); i++ {

		if o.Results[i] != nil {

			if swag.IsZero(o.Results[i]) { // not required
				return nil
			}

			if err := o.Results[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getSearchTorrentsStatusOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getSearchTorrentsStatusOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetSearchTorrentsStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSearchTorrentsStatusOKBody) UnmarshalBinary(b []byte) error {
	var res GetSearchTorrentsStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
