// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewSearchTorrentsParams creates a new SearchTorrentsParams object
// with the default values initialized.
func NewSearchTorrentsParams() SearchTorrentsParams {

	var (
		// initialize parameters with default values

		detailedDefault = bool(false)

		orderbyDefault = string("seeders")
	)

	return SearchTorrentsParams{
		Detailed: &detailedDefault,

		Orderby: &orderbyDefault,
	}
}

// SearchTorrentsParams contains all the bound params for the search torrents operation
// typically these are obtained from a http.Request
//
// swagger:parameters searchTorrents
type SearchTorrentsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Забирать ли детальное описание раздачи
	  In: query
	  Default: false
	*/
	Detailed *bool
	/*Ограничение на кол-во результатов
	  Minimum: 1
	  In: query
	*/
	Limit *int64
	/*
	  In: query
	  Default: "seeders"
	*/
	Orderby *string
	/*Искомый запрос
	  Required: true
	  Max Length: 128
	  Min Length: 2
	  In: query
	*/
	Q string
	/*Номер сезона (для сериалов)
	  Minimum: 1
	  In: query
	*/
	Season *int64
	/*Подсказка, какого типа торренты искать
	  In: query
	*/
	Type *string
	/*Год выхода (для фильмов и сериалов)
	  Minimum: 1900
	  In: query
	*/
	Year *int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSearchTorrentsParams() beforehand.
func (o *SearchTorrentsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDetailed, qhkDetailed, _ := qs.GetOK("detailed")
	if err := o.bindDetailed(qDetailed, qhkDetailed, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qOrderby, qhkOrderby, _ := qs.GetOK("orderby")
	if err := o.bindOrderby(qOrderby, qhkOrderby, route.Formats); err != nil {
		res = append(res, err)
	}

	qQ, qhkQ, _ := qs.GetOK("q")
	if err := o.bindQ(qQ, qhkQ, route.Formats); err != nil {
		res = append(res, err)
	}

	qSeason, qhkSeason, _ := qs.GetOK("season")
	if err := o.bindSeason(qSeason, qhkSeason, route.Formats); err != nil {
		res = append(res, err)
	}

	qType, qhkType, _ := qs.GetOK("type")
	if err := o.bindType(qType, qhkType, route.Formats); err != nil {
		res = append(res, err)
	}

	qYear, qhkYear, _ := qs.GetOK("year")
	if err := o.bindYear(qYear, qhkYear, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDetailed binds and validates parameter Detailed from query.
func (o *SearchTorrentsParams) bindDetailed(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSearchTorrentsParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("detailed", "query", "bool", raw)
	}
	o.Detailed = &value

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *SearchTorrentsParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int64", raw)
	}
	o.Limit = &value

	if err := o.validateLimit(formats); err != nil {
		return err
	}

	return nil
}

// validateLimit carries on validations for parameter Limit
func (o *SearchTorrentsParams) validateLimit(formats strfmt.Registry) error {

	if err := validate.MinimumInt("limit", "query", *o.Limit, 1, false); err != nil {
		return err
	}

	return nil
}

// bindOrderby binds and validates parameter Orderby from query.
func (o *SearchTorrentsParams) bindOrderby(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewSearchTorrentsParams()
		return nil
	}
	o.Orderby = &raw

	if err := o.validateOrderby(formats); err != nil {
		return err
	}

	return nil
}

// validateOrderby carries on validations for parameter Orderby
func (o *SearchTorrentsParams) validateOrderby(formats strfmt.Registry) error {

	if err := validate.EnumCase("orderby", "query", *o.Orderby, []interface{}{"seeders", "title", "size", "quality"}, true); err != nil {
		return err
	}

	return nil
}

// bindQ binds and validates parameter Q from query.
func (o *SearchTorrentsParams) bindQ(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("q", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("q", "query", raw); err != nil {
		return err
	}
	o.Q = raw

	if err := o.validateQ(formats); err != nil {
		return err
	}

	return nil
}

// validateQ carries on validations for parameter Q
func (o *SearchTorrentsParams) validateQ(formats strfmt.Registry) error {

	if err := validate.MinLength("q", "query", o.Q, 2); err != nil {
		return err
	}

	if err := validate.MaxLength("q", "query", o.Q, 128); err != nil {
		return err
	}

	return nil
}

// bindSeason binds and validates parameter Season from query.
func (o *SearchTorrentsParams) bindSeason(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("season", "query", "int64", raw)
	}
	o.Season = &value

	if err := o.validateSeason(formats); err != nil {
		return err
	}

	return nil
}

// validateSeason carries on validations for parameter Season
func (o *SearchTorrentsParams) validateSeason(formats strfmt.Registry) error {

	if err := validate.MinimumInt("season", "query", *o.Season, 1, false); err != nil {
		return err
	}

	return nil
}

// bindType binds and validates parameter Type from query.
func (o *SearchTorrentsParams) bindType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Type = &raw

	if err := o.validateType(formats); err != nil {
		return err
	}

	return nil
}

// validateType carries on validations for parameter Type
func (o *SearchTorrentsParams) validateType(formats strfmt.Registry) error {

	if err := validate.EnumCase("type", "query", *o.Type, []interface{}{"movies", "music", "books", "others"}, true); err != nil {
		return err
	}

	return nil
}

// bindYear binds and validates parameter Year from query.
func (o *SearchTorrentsParams) bindYear(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("year", "query", "int64", raw)
	}
	o.Year = &value

	if err := o.validateYear(formats); err != nil {
		return err
	}

	return nil
}

// validateYear carries on validations for parameter Year
func (o *SearchTorrentsParams) validateYear(formats strfmt.Registry) error {

	if err := validate.MinimumInt("year", "query", *o.Year, 1900, false); err != nil {
		return err
	}

	return nil
}
