// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SearchTorrentsAsyncStatusOKCode is the HTTP code returned for type SearchTorrentsAsyncStatusOK
const SearchTorrentsAsyncStatusOKCode int = 200

/*
SearchTorrentsAsyncStatusOK OK

swagger:response searchTorrentsAsyncStatusOK
*/
type SearchTorrentsAsyncStatusOK struct {

	/*
	  In: Body
	*/
	Payload *SearchTorrentsAsyncStatusOKBody `json:"body,omitempty"`
}

// NewSearchTorrentsAsyncStatusOK creates SearchTorrentsAsyncStatusOK with default headers values
func NewSearchTorrentsAsyncStatusOK() *SearchTorrentsAsyncStatusOK {

	return &SearchTorrentsAsyncStatusOK{}
}

// WithPayload adds the payload to the search torrents async status o k response
func (o *SearchTorrentsAsyncStatusOK) WithPayload(payload *SearchTorrentsAsyncStatusOKBody) *SearchTorrentsAsyncStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search torrents async status o k response
func (o *SearchTorrentsAsyncStatusOK) SetPayload(payload *SearchTorrentsAsyncStatusOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchTorrentsAsyncStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SearchTorrentsAsyncStatusNotFoundCode is the HTTP code returned for type SearchTorrentsAsyncStatusNotFound
const SearchTorrentsAsyncStatusNotFoundCode int = 404

/*
SearchTorrentsAsyncStatusNotFound Задача поиска не найдена

swagger:response searchTorrentsAsyncStatusNotFound
*/
type SearchTorrentsAsyncStatusNotFound struct {
}

// NewSearchTorrentsAsyncStatusNotFound creates SearchTorrentsAsyncStatusNotFound with default headers values
func NewSearchTorrentsAsyncStatusNotFound() *SearchTorrentsAsyncStatusNotFound {

	return &SearchTorrentsAsyncStatusNotFound{}
}

// WriteResponse to the client
func (o *SearchTorrentsAsyncStatusNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// SearchTorrentsAsyncStatusInternalServerErrorCode is the HTTP code returned for type SearchTorrentsAsyncStatusInternalServerError
const SearchTorrentsAsyncStatusInternalServerErrorCode int = 500

/*
SearchTorrentsAsyncStatusInternalServerError Ошибка на стороне сервера

swagger:response searchTorrentsAsyncStatusInternalServerError
*/
type SearchTorrentsAsyncStatusInternalServerError struct {
}

// NewSearchTorrentsAsyncStatusInternalServerError creates SearchTorrentsAsyncStatusInternalServerError with default headers values
func NewSearchTorrentsAsyncStatusInternalServerError() *SearchTorrentsAsyncStatusInternalServerError {

	return &SearchTorrentsAsyncStatusInternalServerError{}
}

// WriteResponse to the client
func (o *SearchTorrentsAsyncStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
