// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SearchTorrentsAsyncCancelOKCode is the HTTP code returned for type SearchTorrentsAsyncCancelOK
const SearchTorrentsAsyncCancelOKCode int = 200

/*
SearchTorrentsAsyncCancelOK OK

swagger:response searchTorrentsAsyncCancelOK
*/
type SearchTorrentsAsyncCancelOK struct {
}

// NewSearchTorrentsAsyncCancelOK creates SearchTorrentsAsyncCancelOK with default headers values
func NewSearchTorrentsAsyncCancelOK() *SearchTorrentsAsyncCancelOK {

	return &SearchTorrentsAsyncCancelOK{}
}

// WriteResponse to the client
func (o *SearchTorrentsAsyncCancelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SearchTorrentsAsyncCancelNotFoundCode is the HTTP code returned for type SearchTorrentsAsyncCancelNotFound
const SearchTorrentsAsyncCancelNotFoundCode int = 404

/*
SearchTorrentsAsyncCancelNotFound Задача поиска не найдена

swagger:response searchTorrentsAsyncCancelNotFound
*/
type SearchTorrentsAsyncCancelNotFound struct {
}

// NewSearchTorrentsAsyncCancelNotFound creates SearchTorrentsAsyncCancelNotFound with default headers values
func NewSearchTorrentsAsyncCancelNotFound() *SearchTorrentsAsyncCancelNotFound {

	return &SearchTorrentsAsyncCancelNotFound{}
}

// WriteResponse to the client
func (o *SearchTorrentsAsyncCancelNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// SearchTorrentsAsyncCancelInternalServerErrorCode is the HTTP code returned for type SearchTorrentsAsyncCancelInternalServerError
const SearchTorrentsAsyncCancelInternalServerErrorCode int = 500

/*
SearchTorrentsAsyncCancelInternalServerError Ошибка на стороне сервера

swagger:response searchTorrentsAsyncCancelInternalServerError
*/
type SearchTorrentsAsyncCancelInternalServerError struct {
}

// NewSearchTorrentsAsyncCancelInternalServerError creates SearchTorrentsAsyncCancelInternalServerError with default headers values
func NewSearchTorrentsAsyncCancelInternalServerError() *SearchTorrentsAsyncCancelInternalServerError {

	return &SearchTorrentsAsyncCancelInternalServerError{}
}

// WriteResponse to the client
func (o *SearchTorrentsAsyncCancelInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
