// Code generated by go-swagger; DO NOT EDIT.

package torrents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// SearchTorrentsURL generates an URL for the search torrents operation
type SearchTorrentsURL struct {
	Limit  *int64
	Q      string
	Season *int64
	Type   *string
	Year   *int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SearchTorrentsURL) WithBasePath(bp string) *SearchTorrentsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *SearchTorrentsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *SearchTorrentsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/torrents/search"

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var limitQ string
	if o.Limit != nil {
		limitQ = swag.FormatInt64(*o.Limit)
	}
	if limitQ != "" {
		qs.Set("limit", limitQ)
	}

	qQ := o.Q
	if qQ != "" {
		qs.Set("q", qQ)
	}

	var seasonQ string
	if o.Season != nil {
		seasonQ = swag.FormatInt64(*o.Season)
	}
	if seasonQ != "" {
		qs.Set("season", seasonQ)
	}

	var typeVarQ string
	if o.Type != nil {
		typeVarQ = *o.Type
	}
	if typeVarQ != "" {
		qs.Set("type", typeVarQ)
	}

	var yearQ string
	if o.Year != nil {
		yearQ = swag.FormatInt64(*o.Year)
	}
	if yearQ != "" {
		qs.Set("year", yearQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *SearchTorrentsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *SearchTorrentsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *SearchTorrentsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on SearchTorrentsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on SearchTorrentsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *SearchTorrentsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
