// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Media Discovery API
//
//	API for Racoon Media Server Project
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/octet-stream
//	  - application/json
//
// swagger:meta
package restapi
