// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for Racoon Media Server Project",
    "title": "Media Discovery API",
    "version": "1.0.0"
  },
  "paths": {
    "/admin/accounts": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "accounts"
        ],
        "summary": "Получить список список акканутов и токенов к внешним системам",
        "operationId": "getAccounts",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "results"
              ],
              "properties": {
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Account"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "accounts"
        ],
        "summary": "Создать новый аккаунт",
        "operationId": "createAccount",
        "parameters": [
          {
            "name": "account",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Account"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "id"
              ],
              "properties": {
                "id": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/admin/accounts/{id}": {
      "delete": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "accounts"
        ],
        "summary": "Удалить аккаунт",
        "operationId": "deleteAccount",
        "parameters": [
          {
            "type": "string",
            "description": "ID аккаунта",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Аккаунт не найден"
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/admin/users": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Получить список пользователей и информацию по ним",
        "operationId": "getUsers",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "results"
              ],
              "properties": {
                "results": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "info": {
                        "type": "string"
                      },
                      "isAdmin": {
                        "type": "boolean"
                      },
                      "lastRequestTime": {
                        "type": "integer"
                      },
                      "reqPerDay": {
                        "type": "number"
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Создать новый ключ пользователя",
        "operationId": "createUser",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "info"
              ],
              "properties": {
                "info": {
                  "type": "string"
                },
                "isAdmin": {
                  "type": "boolean",
                  "default": false
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "id"
              ],
              "properties": {
                "id": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/admin/users/{id}": {
      "delete": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Удалить ключ пользователя",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "string",
            "description": "Ключ пользователя",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Ключ не найден"
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/movies/search": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "description": "Поиск фильмов и сериалов по названию на различных платформах",
        "tags": [
          "movies"
        ],
        "summary": "Поиск фильмов и сериалов",
        "operationId": "searchMovies",
        "parameters": [
          {
            "maxLength": 128,
            "minLength": 2,
            "type": "string",
            "description": "Искомый запрос",
            "name": "q",
            "in": "query",
            "required": true
          },
          {
            "minimum": 1,
            "type": "integer",
            "description": "Ограничение на кол-во результатов",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "results"
              ],
              "properties": {
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/SearchMoviesResult"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/torrents/download": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "description": "Позволяет скачать торрент-файл, с помощью которого можно скачать контент",
        "produces": [
          "application/octet-stream"
        ],
        "tags": [
          "torrents"
        ],
        "summary": "Загрузка торрент-файла",
        "operationId": "downloadTorrent",
        "parameters": [
          {
            "type": "string",
            "description": "Хеш ссылки на результат поиска",
            "name": "link",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Неверный хеш ссылки"
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/torrents/search": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "description": "Поиск фильмов и сериалов по названию на различных платформах",
        "tags": [
          "torrents"
        ],
        "summary": "Поиск контента на торрент-трекерах",
        "operationId": "searchTorrents",
        "parameters": [
          {
            "maxLength": 128,
            "minLength": 2,
            "type": "string",
            "description": "Искомый запрос",
            "name": "q",
            "in": "query",
            "required": true
          },
          {
            "enum": [
              "movies",
              "music",
              "books",
              "others"
            ],
            "type": "string",
            "description": "Подсказка, какого типа инфу искать",
            "name": "type",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "description": "Ограничение на кол-во результатов",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "boolean",
            "default": false,
            "description": "Забирать ли детальное описание раздачи",
            "name": "detailed",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "results"
              ],
              "properties": {
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/SearchTorrentsResult"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Account": {
      "type": "object",
      "required": [
        "service"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "limit": {
          "type": "integer",
          "default": 0
        },
        "login": {
          "type": "string",
          "minLength": 1
        },
        "password": {
          "type": "string"
        },
        "service": {
          "type": "string"
        },
        "token": {
          "type": "string"
        }
      }
    },
    "SearchMoviesResult": {
      "type": "object",
      "required": [
        "id",
        "title"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "genres": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "string"
        },
        "poster": {
          "type": "string"
        },
        "preview": {
          "type": "string"
        },
        "rating": {
          "type": "number"
        },
        "seasons": {
          "type": "integer"
        },
        "title": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "tv-series",
            "film"
          ]
        },
        "year": {
          "type": "integer"
        }
      }
    },
    "SearchTorrentsResult": {
      "type": "object",
      "required": [
        "link"
      ],
      "properties": {
        "link": {
          "type": "string"
        },
        "media": {
          "type": "object",
          "properties": {
            "audio": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "codec": {
                    "type": "string"
                  },
                  "language": {
                    "type": "string"
                  },
                  "voice": {
                    "type": "string"
                  }
                }
              }
            },
            "format": {
              "type": "string"
            },
            "subtitles": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "codec": {
                    "type": "string"
                  },
                  "language": {
                    "type": "string"
                  }
                }
              }
            },
            "video": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "aspectRatio": {
                    "type": "string"
                  },
                  "codec": {
                    "type": "string"
                  },
                  "height": {
                    "type": "integer"
                  },
                  "width": {
                    "type": "integer"
                  }
                }
              }
            }
          }
        },
        "seeders": {
          "type": "integer"
        },
        "size": {
          "type": "integer"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "principal": {
      "type": "object",
      "properties": {
        "admin": {
          "type": "boolean"
        },
        "token": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Фильмы/сериалы",
      "name": "movies"
    },
    {
      "description": "Торренты",
      "name": "torrents"
    },
    {
      "description": "Администрирование пользователей",
      "name": "users"
    },
    {
      "description": "Администрирование аккаунтов",
      "name": "accounts"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for Racoon Media Server Project",
    "title": "Media Discovery API",
    "version": "1.0.0"
  },
  "paths": {
    "/admin/accounts": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "accounts"
        ],
        "summary": "Получить список список акканутов и токенов к внешним системам",
        "operationId": "getAccounts",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "results"
              ],
              "properties": {
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Account"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "accounts"
        ],
        "summary": "Создать новый аккаунт",
        "operationId": "createAccount",
        "parameters": [
          {
            "name": "account",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Account"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "id"
              ],
              "properties": {
                "id": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/admin/accounts/{id}": {
      "delete": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "accounts"
        ],
        "summary": "Удалить аккаунт",
        "operationId": "deleteAccount",
        "parameters": [
          {
            "type": "string",
            "description": "ID аккаунта",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Аккаунт не найден"
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/admin/users": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Получить список пользователей и информацию по ним",
        "operationId": "getUsers",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "results"
              ],
              "properties": {
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ResultsItems0"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Создать новый ключ пользователя",
        "operationId": "createUser",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "info"
              ],
              "properties": {
                "info": {
                  "type": "string"
                },
                "isAdmin": {
                  "type": "boolean",
                  "default": false
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "id"
              ],
              "properties": {
                "id": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/admin/users/{id}": {
      "delete": {
        "security": [
          {
            "key": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Удалить ключ пользователя",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "string",
            "description": "Ключ пользователя",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Ключ не найден"
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/movies/search": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "description": "Поиск фильмов и сериалов по названию на различных платформах",
        "tags": [
          "movies"
        ],
        "summary": "Поиск фильмов и сериалов",
        "operationId": "searchMovies",
        "parameters": [
          {
            "maxLength": 128,
            "minLength": 2,
            "type": "string",
            "description": "Искомый запрос",
            "name": "q",
            "in": "query",
            "required": true
          },
          {
            "minimum": 1,
            "type": "integer",
            "description": "Ограничение на кол-во результатов",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "results"
              ],
              "properties": {
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/SearchMoviesResult"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/torrents/download": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "description": "Позволяет скачать торрент-файл, с помощью которого можно скачать контент",
        "produces": [
          "application/octet-stream"
        ],
        "tags": [
          "torrents"
        ],
        "summary": "Загрузка торрент-файла",
        "operationId": "downloadTorrent",
        "parameters": [
          {
            "type": "string",
            "description": "Хеш ссылки на результат поиска",
            "name": "link",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Неверный хеш ссылки"
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/torrents/search": {
      "get": {
        "security": [
          {
            "key": []
          }
        ],
        "description": "Поиск фильмов и сериалов по названию на различных платформах",
        "tags": [
          "torrents"
        ],
        "summary": "Поиск контента на торрент-трекерах",
        "operationId": "searchTorrents",
        "parameters": [
          {
            "maxLength": 128,
            "minLength": 2,
            "type": "string",
            "description": "Искомый запрос",
            "name": "q",
            "in": "query",
            "required": true
          },
          {
            "enum": [
              "movies",
              "music",
              "books",
              "others"
            ],
            "type": "string",
            "description": "Подсказка, какого типа инфу искать",
            "name": "type",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "description": "Ограничение на кол-во результатов",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "boolean",
            "default": false,
            "description": "Забирать ли детальное описание раздачи",
            "name": "detailed",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "required": [
                "results"
              ],
              "properties": {
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/SearchTorrentsResult"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Ошибка на стороне сервера",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Account": {
      "type": "object",
      "required": [
        "service"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "limit": {
          "type": "integer",
          "default": 0
        },
        "login": {
          "type": "string",
          "minLength": 1
        },
        "password": {
          "type": "string"
        },
        "service": {
          "type": "string"
        },
        "token": {
          "type": "string"
        }
      }
    },
    "ResultsItems0": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "info": {
          "type": "string"
        },
        "isAdmin": {
          "type": "boolean"
        },
        "lastRequestTime": {
          "type": "integer"
        },
        "reqPerDay": {
          "type": "number"
        }
      }
    },
    "SearchMoviesResult": {
      "type": "object",
      "required": [
        "id",
        "title"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "genres": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "string"
        },
        "poster": {
          "type": "string"
        },
        "preview": {
          "type": "string"
        },
        "rating": {
          "type": "number"
        },
        "seasons": {
          "type": "integer"
        },
        "title": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "tv-series",
            "film"
          ]
        },
        "year": {
          "type": "integer"
        }
      }
    },
    "SearchTorrentsResult": {
      "type": "object",
      "required": [
        "link"
      ],
      "properties": {
        "link": {
          "type": "string"
        },
        "media": {
          "type": "object",
          "properties": {
            "audio": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SearchTorrentsResultMediaAudioItems0"
              }
            },
            "format": {
              "type": "string"
            },
            "subtitles": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SearchTorrentsResultMediaSubtitlesItems0"
              }
            },
            "video": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SearchTorrentsResultMediaVideoItems0"
              }
            }
          }
        },
        "seeders": {
          "type": "integer"
        },
        "size": {
          "type": "integer"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "SearchTorrentsResultMedia": {
      "type": "object",
      "properties": {
        "audio": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SearchTorrentsResultMediaAudioItems0"
          }
        },
        "format": {
          "type": "string"
        },
        "subtitles": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SearchTorrentsResultMediaSubtitlesItems0"
          }
        },
        "video": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SearchTorrentsResultMediaVideoItems0"
          }
        }
      }
    },
    "SearchTorrentsResultMediaAudioItems0": {
      "type": "object",
      "properties": {
        "codec": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "voice": {
          "type": "string"
        }
      }
    },
    "SearchTorrentsResultMediaSubtitlesItems0": {
      "type": "object",
      "properties": {
        "codec": {
          "type": "string"
        },
        "language": {
          "type": "string"
        }
      }
    },
    "SearchTorrentsResultMediaVideoItems0": {
      "type": "object",
      "properties": {
        "aspectRatio": {
          "type": "string"
        },
        "codec": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "principal": {
      "type": "object",
      "properties": {
        "admin": {
          "type": "boolean"
        },
        "token": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Фильмы/сериалы",
      "name": "movies"
    },
    {
      "description": "Торренты",
      "name": "torrents"
    },
    {
      "description": "Администрирование пользователей",
      "name": "users"
    },
    {
      "description": "Администрирование аккаунтов",
      "name": "accounts"
    }
  ]
}`))
}
