swagger: '2.0'
info:
  version: 1.3.0
  title: Media Discovery API
  description: API for Racoon Media Server Project
host: 136.244.108.126
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  key:
    type: apiKey
    in: header
    name: x-token

tags:
  - name: movies
    description: Фильмы/сериалы
  - name: torrents
    description: Торренты
  - name: accounts
    description: Администрирование аккаунтов

paths:
  /movies/search:
    get:
      tags:
        - movies
      summary: Поиск фильмов и сериалов
      description: Поиск фильмов и сериалов по названию на различных платформах
      operationId: searchMovies
      parameters:
        - name: q
          in: query
          required: true
          description: Искомый запрос
          type: string
          minLength: 2
          maxLength: 128
        - name: limit
          in: query
          required: false
          description: Ограничение на кол-во результатов
          type: integer
          minimum: 1

      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - results
            properties:
              results:
                type: array
                items:
                  $ref: "#/definitions/SearchMoviesResult"

        '500':
          description: Ошибка на стороне сервера
      security:
        - key: [ ]

  /torrents/search:
    get:
      tags:
        - torrents
      summary: Поиск контента на торрент-трекерах
      description: Поиск раздач на различных платформах
      operationId: searchTorrents
      parameters:
        - name: q
          in: query
          required: true
          description: Искомый запрос
          type: string
          minLength: 2
          maxLength: 128
        - name: type
          in: query
          required: false
          description: Подсказка, какого типа торренты искать
          type: string
          enum:
            - movies
            - music
            - books
            - others
        - name: limit
          in: query
          required: false
          description: Ограничение на кол-во результатов
          type: integer
          minimum: 1
        - name: year
          in: query
          type: integer
          minimum: 1900
          description: Год выхода (для фильмов и сериалов)
        - name: season
          in: query
          type: integer
          minimum: 1
          description: Номер сезона (для сериалов)
        - name: strong
          in: query
          type: boolean
          default: false
          description: Строго отсеивать раздачи, эвристически определенное имя которых не соответствует строчке запроса
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - results
            properties:
              results:
                type: array
                items:
                  $ref: "#/definitions/SearchTorrentsResult"

        '500':
          description: Ошибка на стороне сервера
      security:
        - key: [ ]

  /torrents/download:
    get:
      tags:
        - torrents
      summary: Загрузка торрент-файла
      description: Позволяет скачать торрент-файл, с помощью которого можно скачать контент
      operationId: downloadTorrent
      produces:
        - application/octet-stream
      parameters:
        - name: link
          in: query
          required: true
          description: Хеш ссылки на результат поиска
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary

        '404':
          description: Неверный хеш ссылки

        '500':
          description: Ошибка на стороне сервера
      security:
        - key: [ ]

  /accounts:
    get:
      tags:
        - accounts
      summary: Получить список список акканутов и токенов к внешним системам
      operationId: getAccounts
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - results
            properties:
              results:
                type: array
                items:
                  $ref: "#/definitions/Account"
        '500':
          description: Ошибка на стороне сервера
      security:
        - key: [ ]

    post:
      tags:
        - accounts
      summary: Создать новый аккаунт
      operationId: createAccount
      parameters:
        - name: account
          in: body
          schema:
            $ref: "#/definitions/Account"
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - id
            properties:
              id:
                type: string
        '500':
          description: Ошибка на стороне сервера
      security:
        - key: [ ]

  /accounts/{id}:
    delete:
      tags:
        - accounts
      summary: Удалить аккаунт
      operationId: deleteAccount
      parameters:
        - name: id
          in: path
          description: ID аккаунта
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Аккаунт не найден
        '500':
          description: Ошибка на стороне сервера
      security:
        - key: [ ]

definitions:
  SearchMoviesResult:
    type: object
    required:
      - id
      - title
    properties:
      id:
        type: string
      title:
        type: string
      description:
        type: string
      year:
        type: integer
      poster:
        type: string
      preview:
        type: string
      rating:
        type: number
      genres:
        type: array
        items:
          type: string
      type:
        type: string
        enum:
          - tv-series
          - film
      seasons:
        type: integer

  SearchTorrentsResult:
    type: object
    required:
      - link
      - title
      - size
      - seeders
    properties:
      link:
        type: string
      title:
        type: string
      size:
        type: integer
        minimum: 0
      seeders:
        type: integer
        minimum: 0
      seasons:
        type: array
        description: Количество сезонов в сериале (если это сериал)
        items:
          type: integer
          minimum: 1
      quality:
        type: string
        description: Качество видео
        enum:
          - ""
          - "480p"
          - "720p"
          - "1080p"
          - "2160p"
      rip:
        type: string
        description: Rip для видео
      format:
        type: string
        description: Формат
      voice:
        type: string
        description: Озвучка
      subtitles:
        type: array
        description: Коды языков, на которых предоставлены субтитры
        items:
          type: string

  Account:
    type: object
    required:
      - service
    properties:
      id:
        type: string
      service:
        type: string
      login:
        type: string
        minLength: 1
      password:
        type: string
      token:
        type: string
      limit:
        type: integer
        default: 0
  principal:
    type: object
    properties:
      token:
        type: string
      canManageAccounts:
        type: boolean
